Specify the ntwitter dependency in package.json
The latest hubot-scripts depends on ntwitter - adding it here so
tweet.coffee can access the module and load properly. This is a fix
for the following error:

2013-08-23T14:18:44.667870+00:00 app[web.1]: [Fri Aug 23 2013 14:18:44 GMT+0000 (UTC)] ERROR Unable to load /app/node_modules/hubot-scripts/src/scripts/tweet: Error: Cannot find module 'ntwitter'